# Generated by Django 5.2.5 on 2025-10-10 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mappe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('lagtype', models.CharField(choices=[('sentral', 'Sentralstyret'), ('fylke', 'Fylkeslag'), ('lokal', 'Lokallag')], max_length=10)),
                ('lag_id', models.PositiveIntegerField()),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medlem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornavn', models.CharField(max_length=100, verbose_name='Fornavn')),
                ('etternavn', models.CharField(max_length=100, verbose_name='Etternavn')),
                ('epost', models.CharField(max_length=150, verbose_name='E-post')),
            ],
            options={
                'verbose_name': 'Medlem',
                'verbose_name_plural': 'Medlemmer',
                'ordering': ['etternavn', 'fornavn'],
            },
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=200)),
                ('beskrivelse', models.TextField(blank=True)),
                ('fil', models.FileField(upload_to='dokumenter/%Y/%m/')),
                ('lagtype', models.CharField(choices=[('sentral', 'Sentralstyret'), ('fylke', 'Fylkeslag'), ('lokal', 'Lokallag')], max_length=10)),
                ('lag_id', models.PositiveIntegerField()),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('endret', models.DateTimeField(auto_now=True)),
                ('opplastet_av', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opprettet'],
            },
        ),
        migrations.CreateModel(
            name='Endring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateTimeField(auto_now_add=True)),
                ('beskrivelse', models.CharField(blank=True, max_length=255)),
                ('gammel_fil', models.FileField(blank=True, null=True, upload_to='dokumenter/arkiv/%Y/%m/')),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endringer', to='docs.dokument')),
                ('endret_av', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dato'],
            },
        ),
    ]
