# Generated by Django 5.2.5 on 2025-08-15 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medlem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornavn', models.CharField(max_length=100, verbose_name='Fornavn')),
                ('etternavn', models.CharField(max_length=100, verbose_name='Etternavn')),
                ('epost', models.CharField(max_length=150, verbose_name='E-post')),
            ],
            options={
                'verbose_name': 'Medlem',
                'verbose_name_plural': 'Medlemmer',
                'ordering': ['etternavn', 'fornavn'],
            },
        ),
        migrations.CreateModel(
            name='DocFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=200)),
                ('beskrivelse', models.TextField(blank=True)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('can_read', models.ManyToManyField(blank=True, related_name='docfolders_can_read', to='auth.group', verbose_name='Kan lese (grupper)')),
                ('can_write', models.ManyToManyField(blank=True, related_name='docfolders_can_write', to='auth.group', verbose_name='Kan laste opp (grupper)')),
                ('opprettet_av', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mappe',
                'verbose_name_plural': 'Mapper',
                'ordering': ['navn'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=255)),
                ('fil', models.FileField(upload_to='docs/%Y/%m/')),
                ('merknad', models.TextField(blank=True)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='docs.docfolder')),
                ('opprettet_av', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumenter',
                'ordering': ['-opprettet'],
            },
        ),
    ]
