# Generated by Django 5.2.5 on 2025-09-06 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField()),
                ('text_body', models.TextField(blank=True)),
                ('sist_endret', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Utkast'), ('QUEUED', 'I kø'), ('SENT', 'Sendt')], default='DRAFT', max_length=20)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('opprettet_av', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.emailtemplate')),
            ],
        ),
    ]
