# Generated by Django 5.2.5 on 2025-09-06 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='opprettet_av',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Utkast'), ('QUEUED', 'I kø'), ('SENDING', 'Sender'), ('SENT', 'Sendt')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('medlem_id', models.IntegerField(blank=True, null=True)),
                ('sent_ok', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_try', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox', to='mailings.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'INFO'), ('WARN', 'WARN'), ('ERR', 'ERR')], max_length=8)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('outbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mailings.outbox')),
            ],
        ),
        migrations.AddIndex(
            model_name='outbox',
            index=models.Index(fields=['campaign', 'sent_ok'], name='mailings_ou_campaig_a01e2e_idx'),
        ),
        migrations.AddConstraint(
            model_name='outbox',
            constraint=models.UniqueConstraint(fields=('campaign', 'to_email'), name='uniq_campaign_email'),
        ),
    ]
