# Generated by Django 5.2.5 on 2025-08-18 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fylke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(db_index=True, max_length=2, unique=True)),
                ('navn', models.CharField(max_length=64)),
                ('gyldig_fra', models.DateField(blank=True, null=True)),
                ('gyldig_til', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nummer'],
            },
        ),
        migrations.CreateModel(
            name='Postnummer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(db_index=True, max_length=4, unique=True)),
                ('poststed', models.CharField(max_length=64)),
                ('kategori', models.CharField(blank=True, choices=[('G', 'Gate/postboks'), ('B', 'Postboksanlegg'), ('S', 'Serviceboks'), ('F', 'Felles')], max_length=1)),
            ],
            options={
                'ordering': ['nummer'],
            },
        ),
        migrations.CreateModel(
            name='Kommune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(db_index=True, max_length=4, unique=True)),
                ('navn', models.CharField(max_length=128)),
                ('gyldig_fra', models.DateField(blank=True, null=True)),
                ('gyldig_til', models.DateField(blank=True, null=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('fylke', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kommuner', to='geo.fylke')),
            ],
            options={
                'ordering': ['nummer'],
            },
        ),
        migrations.CreateModel(
            name='PostnummerKommune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primar', models.BooleanField(default=False)),
                ('kommune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postnumre', to='geo.kommune')),
                ('postnummer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommuner', to='geo.postnummer')),
            ],
            options={
                'unique_together': {('postnummer', 'kommune')},
            },
        ),
    ]
