# Generated by Django 5.2.5 on 2025-08-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fylke',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='fylke',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fylke',
            name='homepage_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fylke',
            name='homepage_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fylke',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/fylke/'),
        ),
        migrations.AddField(
            model_name='fylke',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
