# Generated by Django 5.2.5 on 2025-08-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_add_slug_and_fill_fylke'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fylke',
            options={'ordering': ['navn'], 'verbose_name_plural': 'Fylker'},
        ),
        migrations.RemoveField(
            model_name='fylke',
            name='gyldig_fra',
        ),
        migrations.RemoveField(
            model_name='fylke',
            name='gyldig_til',
        ),
        migrations.RemoveField(
            model_name='fylke',
            name='nummer',
        ),
        migrations.AlterField(
            model_name='fylke',
            name='navn',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
