# Generated by Django 5.2.5 on 2025-08-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_alter_fylke_options_remove_fylke_gyldig_fra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fylke',
            name='homepage_public',
            field=models.BooleanField(default=True),
        ),
    ]
