# Generated by Django 5.2.5 on 2025-08-30 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0004_alter_fylke_options_remove_fylke_gyldig_fra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FylkeSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(blank=True, max_length=200)),
                ('intro', models.TextField(blank=True)),
                ('hero_bilde', models.ImageField(blank=True, null=True, upload_to='logos/fylkehero/')),
                ('offentlig', models.BooleanField(default=True)),
                ('fylke', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='geo.fylke')),
            ],
            options={
                'verbose_name': 'Fylke-site',
                'verbose_name_plural': 'Fylke-sites',
            },
        ),
    ]
