# Generated by Django 5.2.5 on 2025-08-18 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lokallag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=128, unique=True)),
                ('fylke', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lokallag', to='geo.fylke')),
                ('kommune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lokallag', to='geo.kommune')),
            ],
            options={
                'ordering': ['navn'],
            },
        ),
        migrations.CreateModel(
            name='Medlem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornavn', models.CharField(max_length=100)),
                ('etternavn', models.CharField(max_length=100)),
                ('epost', models.EmailField(max_length=254, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('kommune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medlemmer', to='geo.kommune')),
                ('postnummer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medlemmer', to='geo.postnummer')),
            ],
            options={
                'ordering': ['etternavn', 'fornavn'],
            },
        ),
        migrations.CreateModel(
            name='Medlemskap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdato', models.DateField(auto_now_add=True)),
                ('sluttdato', models.DateField(blank=True, null=True)),
                ('lokallag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.lokallag')),
                ('medlem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.medlem')),
            ],
            options={
                'unique_together': {('medlem', 'lokallag')},
            },
        ),
        migrations.AddField(
            model_name='medlem',
            name='lokallag',
            field=models.ManyToManyField(related_name='medlemmer', through='members.Medlemskap', to='members.lokallag'),
        ),
    ]
