# Generated by Django 5.2.5 on 2025-08-18 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lokallag',
            options={},
        ),
        migrations.RenameField(
            model_name='medlem',
            old_name='opprettet',
            new_name='registrert',
        ),
        migrations.RemoveField(
            model_name='medlemskap',
            name='sluttdato',
        ),
        migrations.AddField(
            model_name='medlem',
            name='fodselsdato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medlem',
            name='telefon',
            field=models.CharField(db_index=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medlem',
            name='verve_kilde',
            field=models.CharField(choices=[('self', 'Selvregistrering'), ('verver', 'Vervet av')], default='self', max_length=10),
        ),
        migrations.AddField(
            model_name='medlem',
            name='verver_navn',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='medlem',
            name='verver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='epost',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='kommune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.kommune'),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='postnummer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.postnummer'),
        ),
    ]
