# Generated by Django 5.2.5 on 2025-08-19 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_lokallag_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lokallag',
            options={'ordering': ['navn'], 'verbose_name': 'Lokallag', 'verbose_name_plural': 'Lokallag'},
        ),
        migrations.AlterModelOptions(
            name='medlem',
            options={'ordering': ['etternavn', 'fornavn'], 'verbose_name': 'Medlem', 'verbose_name_plural': 'Medlemmer'},
        ),
        migrations.AlterModelOptions(
            name='medlemskap',
            options={'verbose_name': 'Medlemskap', 'verbose_name_plural': 'Medlemskap'},
        ),
        migrations.AlterField(
            model_name='medlem',
            name='lokallag',
            field=models.ManyToManyField(blank=True, related_name='medlemmer', through='members.Medlemskap', to='members.lokallag'),
        ),
        migrations.AlterField(
            model_name='medlemskap',
            name='lokallag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medlemskap', to='members.lokallag'),
        ),
        migrations.AlterField(
            model_name='medlemskap',
            name='medlem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medlemskap', to='members.medlem'),
        ),
    ]
