# Generated by Django 5.2.5 on 2025-08-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_lokallag_options_alter_medlem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medlem',
            options={'ordering': ['etternavn', 'fornavn'], 'permissions': [('approve_member', 'Kan godkjenne selvregistreringer')], 'verbose_name': 'Medlem', 'verbose_name_plural': 'Medlemmer'},
        ),
    ]
