# Generated by Django 5.2.5 on 2025-08-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_medlem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMedlem',
            fields=[
            ],
            options={
                'verbose_name': 'Selvregistrering til godkjenning',
                'verbose_name_plural': 'Selvregistreringer til godkjenning',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('members.medlem',),
        ),
    ]
