# Generated by Django 5.2.5 on 2025-08-24 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('members', '0005_pendingmedlem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fylkeslag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=128)),
                ('epost', models.EmailField(blank=True, max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('leder_navn', models.CharField(blank=True, max_length=128)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('fylke', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fylkeslag', to='geo.fylke')),
            ],
            options={
                'verbose_name': 'Fylkeslag',
                'verbose_name_plural': 'Fylkeslag',
                'ordering': ['fylke__navn'],
            },
        ),
    ]
