# Generated by Django 5.2.5 on 2025-08-24 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_fylkeslag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fylkeslagsmedlemskap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolle', models.CharField(choices=[('leder', 'Leder'), ('styre', 'Styremedlem'), ('medlem', 'Medlem')], default='medlem', max_length=20)),
                ('startdato', models.DateField(auto_now_add=True)),
                ('fylkeslag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.fylkeslag')),
                ('medlem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.medlem')),
            ],
            options={
                'unique_together': {('medlem', 'fylkeslag')},
            },
        ),
    ]
