# Generated by Django 5.2.5 on 2025-08-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_fylkeslagsmedlemskap'),
    ]

operations = [
    migrations.AddField(
        model_name="lokallag",
        name="contact_phone",
        field=models.CharField(max_length=50, blank=True),
    ),
    migrations.AddField(
        model_name="lokallag",
        name="homepage_intro",
        field=models.TextField(blank=True),
    ),
    migrations.AddField(
        model_name="lokallag",
        name="homepage_title",
        field=models.CharField(max_length=200, blank=True),
    ),
    migrations.AddField(
        model_name="lokallag",
        name="logo",
        field=models.ImageField(upload_to="logos/lokal/", blank=True, null=True),
    ),
    migrations.AddField(
        model_name="lokallag",
        name="slug",
        field=models.SlugField(max_length=140, blank=True, null=True),
    ),
]
