# Generated by Django 5.2.5 on 2025-08-27 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_alter_fylke_options_remove_fylke_gyldig_fra_and_more'),
        ('members', '0010_make_slug_unique'),
    ]

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_alter_fylke_options_remove_fylke_gyldig_fra_and_more'),
        ('members', '0010_make_slug_unique'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # VIKTIG: ingen DB-endringer her
            state_operations=[
                migrations.AddField(
                    model_name='lokallag',
                    name='contact_email',
                    field=models.EmailField(blank=True, null=True, max_length=254),
                ),
                migrations.AddField(
                    model_name='lokallag',
                    name='contact_phone',
                    field=models.CharField(blank=True, max_length=50),
                ),
                migrations.AddField(
                    model_name='lokallag',
                    name='homepage_intro',
                    field=models.TextField(blank=True),
                ),
                migrations.AddField(
                    model_name='lokallag',
                    name='homepage_title',
                    field=models.CharField(blank=True, max_length=200),
                ),
                migrations.AddField(
                    model_name='lokallag',
                    name='logo',
                    field=models.ImageField(blank=True, null=True, upload_to='logos/lokal/'),
                ),
                migrations.AlterField(
                    model_name='lokallag',
                    name='fylke',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.fylke'),
                ),
                migrations.AlterField(
                    model_name='lokallag',
                    name='kommune',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.kommune'),
                ),
                migrations.AlterField(
                    model_name='lokallag',
                    name='navn',
                    field=models.CharField(max_length=150),
                ),
            ],
        ),
    ]
