# Generated by Django 5.2.5 on 2025-08-29 09:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_lokallag_contact_email_lokallag_contact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rolle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('kode', models.SlugField(blank=True, max_length=100)),
                ('scope', models.CharField(choices=[('lokal', 'Lokallag'), ('fylke', 'Fylkeslag'), ('sentral', 'Sentralstyre')], max_length=10)),
                ('rang', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ('scope', 'rang', 'navn'),
                'unique_together': {('kode', 'scope')},
            },
        ),
        migrations.CreateModel(
            name='SentralstyreMedlemskap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdato', models.DateField(default=django.utils.timezone.now)),
                ('sluttdato', models.DateField(blank=True, null=True)),
                ('medlem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentralverv', to='members.medlem')),
                ('rolle', models.ForeignKey(limit_choices_to={'scope': 'sentral'}, on_delete=django.db.models.deletion.PROTECT, to='members.rolle')),
            ],
            options={
                'verbose_name': 'Sentralstyre-medlemskap',
                'verbose_name_plural': 'Sentralstyre-medlemskap',
                'ordering': ('-startdato',),
            },
        ),
    ]
